### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by mark-rodgers** [agentdr8/saax#1]
Does this work with the latest version of AA?
At time of posting v2.1.704904

**Comment by agentdr8** [comment]
I saw posts on XDA saying it isn't working on the latest AA release. I haven't had a chance to investigate why, but I'm guessing Google has changed some class and/or method names around. 

If you have a chance to post a debug.log from Xposed that would help out greatly.

**Comment by mark-rodgers** [comment]
I actually have not even tried, I was just asking before even attempting. But I also just remembered afaik Xposed isn't available on Nougat, and I'm using a Pixel XL, so regardless, I'll have to wait until Xposed is released before I can test this out :(

Side note, in the latest AA release I'm actually not even able to bypass the 6 touch limit even when I'm not moving which is rather annoying. It tells me to park the card to continuing browsing, WHILE I'm parked. #thanksGoogle
