### ISSUE TITLE
AA 3

### ISSUE THREAD

**Issue by poxin13** [agentdr8/saax#2]
Recently discovered this but unfortunately not working on latest AA v3+. Any plans for updates to the module?

**Comment by agentdr8** [comment]
Yes, I do plan on updating for the 3.x series. I'm currently in the middle of relocating, so it'll be a while before I can focus on it.

**Comment by poxin13** [comment]
Thanks for this, working great. Makes AA usable again when trying to find music. Stock AA should at least ask if you are a passenger and let you continue browsing like 99% of everything else out there.
